---
version: "2.0"

services:
  node:
    image: ghcr.io/stake-frites/some-tracker:latest
    expose:
      - port: 80
        accept:
          - some-tracker.stakefrites.co
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 100Mi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1weeu5yuj8n23hd87wsdxqqgfmzzz9zt6zrr52c
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 3
